config/routes.rb
Rails.application.routes.draw do

  resources :spare_part_solds
  resources :spare_parts
  resources :quotations
  resources :hydraulic_jacks
  resources :pull_types
  resources :brake_types
  resources :reinforcement_types
  resources :fender_types
  resources :turn_types
  resources :divition_types
  resources :suspension_types
  resources :roof_types
  resources :colors
  resources :trailer_widths
  resources :trailer_lengths
  resources :trailer_heights
  resources :ramp_types
  resources :redila_types
  resources :floor_types
  resources :capacities
  resources :trailer_types
  resources :status_shippings
  resources :fiscal_vouchers
  resources :trailers
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :offices
  get 'items/next_maintenances', to: 'items#next_maintenances', as: :items_next_maintenances
  put 'items/:id/change_maintenance_done/:value', to: 'items#change_maintenance_done', as: :items_change_maintenance_done

  get 'reporter', to: 'items#reporter', as: :reporter

  get '/branches/departments', to: 'branches#departments'

  get '/categories/sub_categories', to: 'categories#sub_categories'

  get '/branches/:id/departments', to: 'branches#departments_for_select'

  get '/terminos_condiciones', to: 'home#terminos_condiciones'

  get '/user_employee_nomber/:employee_nomber', to: 'application#user_employee_nomber'

  delete 'departments/:department_id/employee/:id', to: 'departments#destroy_employee', as: :destroy_department_employee
  delete '/destroy_category/:category_id/:trailer_type_id', to: 'trailer_types#destroy_category'



  mount ActionCable.server, at: '/cable'

  # mount Plutus::Engine => "/plutus", :as => "plutus"

  resources :items
  resources :providers
  resources :maintenances
  resources :status_items
  resources :brands
  resources :sub_categories
  resources :categories
  resources :departments
  resources :branches
  resources :companies
  resources :permissions
  resources :roles
  resources :work_articles


  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do

      put 'sign_up_guest' => 'users_manager#sign_up_guest'
      put 'save_token' => 'users_manager#save_token'
      put 'login_user' => 'users_manager#login_user'
    end
  end

  devise_for :users,
             controllers: {sessions: 'users/sessions',
                           confirmations: 'users/confirmations',
                           unlocks: 'users/unlocks',
                           registrations: 'users/registrations',
                           passwords: 'users/passwords',
                           password_expired: 'users/password_expired'},
             path: '/',
             path_names: {sign_in: 'login',
                          sign_out: 'logout'}

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
      get '/report_to_client/:id' => 'items#report_to_client', :defaults => {:format => 'pdf'}
    end
    get '/users/sessions/remolques_new' => 'users/sessions#remolques_new', as: :login_remolques

    authenticate :user do
      put '/users/assign_item' => 'users/registrations#assign_item', as: :users_assign_item
      put '/users/unassign_item' => 'users/registrations#unassign_item', as: :users_unassign_item

      # Shows all users.
      get '/users', to: 'users/registrations#index', as: :user_registrations
      get '/employees', to: 'users/registrations#employees_index', as: :employees
      get '/employee/:id/assign_work_articles', to: 'users/registrations#assign_work_articles',
          as: :employee_assign_work_articles
      post '/employee/add_work_article', to: 'users/registrations#add_work_article',
           as: :employee_add_work_article
      match '/employee/remove_work_article', to: 'users/registrations#remove_work_article',
            as: :employee_remove_work_article, via: [:patch, :put]
      get '/search_work_articles/:id/:search_type', to: 'users/registrations#search_work_articles',
          as: :search_work_articles

      # Create new users.
      get '/users/new', to: 'users/registrations#new_user', as: :new_user
      get '/employee/new', to: 'users/registrations#new_employee', as: :new_employee
      post '/users', to: 'users/registrations#create_user', as: :create_user



      # Create new users.
      get '/users/employee_department', to: 'users/registrations#new_employee_department', as: :new_employee_department
      #post '/users', to: 'users/registrations#create_user', as: :create_user

      #Get Branch for user
      get '/get_branch_user/:id', to: 'branches#get_branch_user'

      #GET Category and sub category by trailer
      get '/category_subcategory/:id', to: 'trailers#get_category_subcategory'

      # Edit page for a user profile.
      get '/users/edit', to: 'users/registrations#edit', as: :edit_profile
      match '/users', to: 'users/registrations#update_profile', as: :update_profile, via: [:patch, :put]
      match '/users/update_password', to: 'users/registrations#update_password', as: :update_password, via: [:patch, :put]


      # User image
      match '/users/:id/get_user_image', to: 'users/registrations#get_user_image', as: :get_user_image, via: [:patch, :put]

      # Edit page for all users.
      get '/users/:id/edit', to: 'users/registrations#edit_user', as: :edit_user
      match '/users/:id', to: 'users/registrations#update_user', as: :update_user, via: [:patch, :put]

      # Show page for a user.
      get '/users/:id', to: 'users/registrations#show', as: :user

      # Edit a user password.
      get '/users/:id/change_password', to: 'users/registrations#change_password', as: :change_password
      match 'save_password/:id', to: 'users/registrations#save_password', as: :save_password,
            via: [:patch, :put]

      # Destroys a user
      delete '/users/:id', to: 'users/registrations#destroy', as: :destroy_user_registration

      # Gets a JS response with all controller actions.
      get '/permissions/new/get_controller_actions', to: 'permissions#get_controller_actions', as: :get_controller_actions

      # Posts seed data from permissions in relation with their role.
      post '/permissions/generate_seeds', to: 'permissions#generate_seeds', as: :generate_seeds

      # Displays a role with every permission granted.
      get '/roles/:role_id/permissions', to: 'roles#role_permissions', as: :role_permissions

      # Creates a relationship between roles and permissions.
      post '/roles/:role_id/assign_permissions', to: 'roles#assign_permissions', as: :assign_permissions

      # Sets the language to spanish.
      get '/set_language/spanish'

      # Sets the language to english.
      get '/set_language/english'


      #Rutas para la generación de reportes
      get 'reports/sales' => 'reports#report_sales'
      #Rutas para enviar correos
      get '/send_email/:id' => 'items#send_email'


      get '/income_statement' => 'items#income_statement'


      #add Files to Items details from angular
      post '/item_file/:id' => 'items#create_file'
      post '/item_maintenance/:id' => 'items#create_maintenance'
      get '/items_excel' => 'items#items_excel'
      get '/item_qr/:id' => 'items#item_qr', as: :item_qr
      get 'report/sales/:trailers' => 'items#new_report_sales', :defaults => {:format => 'pdf'}
      get 'report/item_sale/:id' => 'items#report_item_sale', :defaults => {:format => 'pdf'}
      get 'download_bill/:id' => 'items#download_bill' #, :defaults => {:format => 'pdf'}


      #add Files to Quotation  from angular
      get 'report/quotation/:id' => 'quotations#report_quotation' #, :defaults => {:format => 'pdf'}

      get 'items_import' => 'items#items_imports'
      resources :items do
        collection { post :import }
      end



      get '/get_maintenances/:id' => 'items#get_maintenances'
      get '/get_files/:id' => 'items#get_files'



      #Regresa la info del articulo que se selecciona en la venta
      get '/cities/:id', to: 'branches#cities'


      get '/next_code_department/:branch_id', to:'branches#next_code'

      #Rutas extras para Departamentos
      get '/departments/:id/items/:employee_id' => 'departments#employee_items', as: :departments_employee_items
      get 'departments_by_branch/:id' => 'departments#get_departments_by_branch'
      get 'all_departments_by_branch/:id' => 'departments#get_all_departments_by_branch'


      #Rutas extras para subcategorias
      get 'subcategory_by_category/:id' => 'sub_categories#get_subcategory_by_category'

      #Ruta para orders
      get 'orders' => 'items#orders'
      get 'orders_shipped' => 'items#orders_shipped'
      get 'new_order' => 'items#new_order', as: :new_order
      get 'edit_order/:id' => 'items#edit_order', as: :edit_order

      #Ruta para cotizaciones
      # get 'quotations' => 'items#quotations'
      # get 'new_quotation' => 'items#new_quotation', as: :new_quotation
      # get 'edit_quotation/:id' => 'items#edit_quotation', as: :edit_quotation

      #Ruta para ventas
      get 'sales' => 'items#sales'
      
      #api
      namespace :api, defaults: {format: 'json'} do
        namespace :v1 do        
          get 'get_items' => 'inventory_manager#get_items'
          get 'get_items_not_sell/:user_id' => 'inventory_manager#get_items_not_sell'
          get 'get_items_sell/:user_id' => 'inventory_manager#get_items_sell'
          get 'get_items_order/:user_id' => 'inventory_manager#get_items_order'
          get 'get_orders_shipped/:user_id' => 'inventory_manager#get_orders_shipped'
          get 'get_branches' => 'inventory_manager#get_branches'
          get 'get_cities' => 'inventory_manager#get_cities'
          get 'get_states' => 'inventory_manager#get_states'
          get 'get_trailers' => 'inventory_manager#get_trailers'

app/models/branch.rb
# == Schema Information
#
# Table name: branches
#
#  id          :integer          not null, primary key
#  name        :string
#  description :string
#  city_id     :integer
#  company_id  :integer
#  manager_id  :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  state_id    :integer
#  code        :string
#  last_code   :integer
#  fleet_cost  :decimal(, )      default(0.0)
#

class Branch < ApplicationRecord
  belongs_to :company, optional: true

  # belongs_to :state , :class_name => 'State' , foreign_key: 'state_id'
  belongs_to :city , :class_name => 'City' , foreign_key: 'city_id'

  belongs_to :manager, class_name: 'User', foreign_key: 'manager_id', optional: true

  has_one :state, through: :city


  has_many :departments

  has_many :items, through: :departments
  validates :fleet_cost, numericality: { less_than_or_equal_to: 100 }



  # delegate :name, to: :company, prefix: true, allow_nil: true
end

app/controllers/branches_controller.rb
class BranchesController < ApplicationController
  before_action :set_branch, only: [:show, :edit, :update, :destroy]


  # GET /branches
  # GET /branches.json
  def index
    @search_branches = policy_scope(Branch).ransack(params[:q])
    @branches = @search_branches.result.paginate(page: params[:page], per_page: 20)
  end

  # GET /branches/1
  # GET /branches/1.json
  def show
  end

  # GET /branches/new
  def new
    @branch = Branch.new
  end

  # GET /branches/1/edit
  def edit
  end

  # POST /branches
  # POST /branches.json
  def create
    @branch = Branch.new(branch_params)

    respond_to do |format|
      if @branch.save
        format.html { redirect_to branches_path, notice: 'La sucursal se creó correctamente.' }
        format.json { render :show, status: :created, location: @branch }
      else
        format.html { render :new }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /branches/1
  # PATCH/PUT /branches/1.json
  def update
    respond_to do |format|
      if @branch.update(branch_params)
        format.html { redirect_to branches_path, notice: 'La sucursal se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @branch }
      else
        format.html { render :edit }
        format.json { render json: @branch.errors, status: :unprocessable_entity }
      end
    end
  end

  def departments
    @branches = policy_scope(Branch).find(params[:branch_ids])


    render json: @branches.to_json(include: :departments), status: :ok
  end

  def departments_for_select
    @departments = policy_scope(Department).where(branch_id: params[:id])

    render json: @departments.to_json(include: [:employees, :manager, branch: {include: [user: {methods: :full_name}]}]), status: :ok
  end

  # DELETE /branches/1
  # DELETE /branches/1.json
  def destroy
    respond_to do |format|
      if @branch.destroy
        format.html { redirect_to branches_url, notice: 'La sucursal fue eliminada.' }
        format.json { render json: true }
      else
        format.json { render json: false }

      end
    end
  end

  def cities
    @cities = City.where(state_id: params[:id]).order(:name)
    render json: @cities.to_json
  end


  def next_code
    @branch = Branch.find(params[:branch_id])
    last_code = @branch.last_code + 1
    value = "#{@branch.code}-#{last_code.to_s}"
    render json: value.to_json
  end

  def get_branch_user
    @user = User.find(params[:id])
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_branch
    @branch = Branch.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def branch_params
    params.require(:branch).permit(:name, :description, :company_id, :manager_id, :city_id, :state_id, :code, :fleet_cost)
  end
end

app/helpers/branches_helper.rb
module BranchesHelper
end

app/views/branches/_form.html.slim
= form_for(branch, branch: 'form', html: {class: 'form-horizontal'}, validate: true) do |f|
  - if @branch.errors.any?
    #error_explanation
      h2 = "#{pluralize(branch.errors.count, "error")} prohibited this branch from being saved:"
      ul
        - @branch.errors.full_messages.each do |message|
          li = message
  .box-body
    - if selected_company_id.equal?(0)
      .row.form-group
        = f.label :company, class: 'col-sm-2 control-label'
        .col-sm-10
          = f.collection_select(:company_id, policy_scope(Company), :id, :name,
                  {prompt: t('helpers.select.prompt')}, {class: 'form-control'})
    - else
      .row.form-group
        = f.label :company, class: 'col-sm-2 control-label'
        .col-sm-10
          = f.label selected_company, class: 'control-label h2.page-header text-uppercase'
          = f.hidden_field :company_id, value: Company.first.id


    .row.form-group
      = f.label :name, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_field :name, class: 'form-control', placeholder: t('.name'), autofocus: true
    .row.form-group
      = f.label :state, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.collection_select(:state_id, State.all, :id, :name,
                {prompt: t('helpers.select.prompt')}, {class: 'form-control'})
    .row.form-group
      = f.label :city, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.collection_select(:city_id, City.all.uniq, :id, :name,
                {prompt: t('helpers.select.prompt')}, {class: 'form-control', :disabled => "disabled"})
    .row.form-group
      = f.label :manager_id, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.collection_select(:manager_id, User.all, :id, :full_name,
                {prompt: t('helpers.select.prompt')}, {class: 'form-control'})
    - unless branch.name == 'Cuauhtemoc'
      .row.form-group
        = f.label "Costo de Flete" , class: 'col-sm-2 control-label'
        .col-sm-10
          .input-group
            = f.number_field :fleet_cost, class: 'form-control text_field', step: 5.0, min:0.0, max:100
            span.input-group-addon %
  .box-footer
    = f.button "<i class='fa fa-floppy-o'></i> #{t('helpers.submit.submit', model: t('.resource'))}".html_safe,
            class: 'btn btn-primary btn-flat', type: 'submit'
    - if has_policy(Branch, %w(index))
      = link_to branches_path, class: 'btn btn-default btn-flat' do
        i.fa.fa-list
        =< t('.back')

  javascript:
    $(document).ready(function () {
      $('.datepicker').datepicker({
        format: 'dd/mm/yyyy',
        language: "es",
        beforeShow: function () {
          $('.datepicker').addClass('datepicker');
        }
      });

      jQuery(document).ready(function () {
        jQuery('#branch_state_id').change(function () {
          var data = $('#branch_state_id').val();
          $("#branch_city_id").prop( "disabled", true );
          $('#branch_city_id').html('');
          if (data != "") {
            $.ajax({
              type: "GET",
              url: "/cities/" + data,
              data: data,
              success: function (result) {
                $("#branch_city_id").prop( "disabled", false );
                $('#branch_city_id').html('');
                for (var i in result) {
                  var id = result[i].id;
                  var name = result[i].name;
                  $("#branch_city_id").append(new Option(name, id));

                }
              }
            });
          } else {
            $('#price_item').text("");
          }
        });
      }); //Fin del document ready
    }); //Fin del document ready

app/views/branches/edit.html.slim
section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-header.with-border
          h3.box-title
            = t('.title')
        = render 'form', branch: @branch

app/views/branches/index.html.slim
p.flash-notice
  = params[:notice]
section.content ng-controller="branchesController"
  .row
    .col-xs-12
      .box.box-primary
        .box-header.with-border
          .row
            .col-xs-6.col-md-8.col-lg-8
              h3.box-title
                = t('.title')
            .col-xs-6.col-md-4.col-lg-4
              .box-tools.pull-right
                = search_form_for @search_branches do |f|
                  .input-group.input-group-sm.search
                    / = f.text_field :name_or_description_or_company_name_or_city_name_or_state_name_or_user_first_name_or_user_last_name_or_user_maiden_name_cont, class: 'form-control',
                             placeholder: t('helpers.search')
                    .input-group-btn
                      button [class="btn btn-default" type="submit"]
                        i [class="fa fa-search"]
                = link_to new_branch_path, class: 'btn btn-sm btn-flat btn-success', title: t('.new_branch') do
                  i.fa.fa-plus
                  span.hidden-xs
                    =< t('.new_branch')

            .box-body
              .dataTables_wrapper
                .row
                  .col-sm-12
                    .table-responsive
                      table.table.table-bordered.table-hover.dataTable
                        thead
                          tr
                            th = t('.name')
                            th = t('.state')
                            th = t('.city')
                            th = t('.manager')
                            th = t('Flete')
                            th.actions_header
                              = t('helpers.actions')
                          tbody
                            - @branches.each do |branch|
                              tr.show_actions
                                td = branch.name
                                td = branch.state.name if branch.state.present?
                                td = branch.city.name if branch.city.present?
                                td = branch.manager.present?? branch.manager.try(:full_name) : 'SIN ASIGNAR'
                                td = "#{branch.fleet_cost}%"
                                td
                                  .actions
                                    - if has_policy(Branch, %w(show))
                                      = link_item '<i class="fa fa-search"></i>'.html_safe, branch_path(branch),
                                             class: 'btn btn-xs btn-success btn-flat', title: t('helpers.show')
                                    = link_item '<i class="fa fa-edit"></i>'.html_safe, edit_branch_path(branch),
                                            class: 'btn btn-xs btn-primary btn-flat', title: t('helpers.edit')
                                    - if has_policy(Branch, %w(destroy))
                                      a ng-click="delete_branch(#{branch.id})" class="btn btn-xs btn-danger btn-flat btn-destroy"
                                        i.fas.fa-trash
                                      /= link_to '<i class="fa fa-trash-o"></i>'.html_safe, '#',  method: :delete,title: t('helpers.destroy'),
                                              class: 'btn btn-xs btn-danger btn-flat btn-destroy',
                                              data: {'resource' => :branches, 'resource-id' => branch.id,
                                                      'confirm' => t('questions.destroy', resource: t('.resource'),
                                                              name: branch.name)}
          .row
            .col-sm-5
              .dataTables_info
                = pluralize(@branches.count, t('.one'), t('.other'))
            .col-sm-7
              .dataTables_paginate.paging_simple_numbers
                = custom_paginator(@branches)

app/views/branches/new.html.slim
section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-header.with-border
          h3.box-title
            = t('.title')
        = render 'form', branch: @branch

app/views/branches/show.html.erb
<section class="content" ng-controller="branchesController">
  <div class="row">
    <div class="col-md-12">
      <div class="box box-primary">
        <div class="box-body box-profile">
          <h3 class="profile-username text-center"><%= @branch.name %></h3>
          <ul class="list-group list-group-unbordered">
            <li class="list-group-item">
              <b>Gerente</b> <a class="pull-right"><%= @branch.try(:manager).try(:full_name)%></a>
            </li>
            <li class="list-group-item">
              <b>Ciudad</b> <a class="pull-right"><%= @branch.try(:city).try(:name)%></a>
            </li>
            <li class="list-group-item">
              <b>Estado</b> <a class="pull-right"><%= @branch.try(:state).try(:name)%></a>
            </li>
            <li class="list-group-item">
              <b>Estatus</b> <a class="pull-right">Disponible</a>
            </li>
            <% unless @branch.name == "Cuauhtemoc" %>
              <li class="list-group-item">
                <b>Costo de Flete</b> <a class="pull-right"><%= "#{@branch.fleet_cost}%"   %></a>
              </li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>

    <div class="col-md-12">
      <div class="nav-tabs-custom">
        <ul class="nav nav-tabs">
          <li><a href="#timeline" data-toggle="tab">Artículos</a></li>
        </ul>
        <div class="tab-content">
          <div class="box-body">
            <div class="dataTables_wrapper">
              <div class="row">
                <div class="col-sm-12">
                  <div class="table-responsive">
                    <table class="table table-bordered table-hover dataTable">
                      <thead>
                        <tr>
                          <th>Numero de Serie</th>
                          <th> Modelo</th>
                          <th>Descripción</th>
                        </tr>
                      </thead>
                      <tbody>
                      <% @branch.items.each do |item| %>
                      <tr class="show_actions">
                        <td><%= item.serial_number %></td>
                        <td><%= item.try(:model) %></td>
                        <td><%= item.categories_description %></td>
                        <td>
                          <div class="item.status_item.name if item.status_item.present?">
                            <%= link_item '<i class="fa fa-search"></i>'.html_safe, item_path(item), title: t('helpers.show'),
                                          class: 'btn btn-xs btn-success btn-flat'  %>
                            <%= link_item '<i class="fa fa-edit"></i>'.html_safe, edit_item_path(item),
                                          class: 'btn btn-xs btn-primary btn-flat', title: t('helpers.edit')  %>
                            <% unless current_user.user_employee? %>
                              <a ng-click="delete_item(<%= item.id %>)" class="btn btn-xs btn-danger btn-flat btn-destroy">
                                <i class="fas fa-trash"></i>
                              </a>
                            <% end  %>
                          </div>

                        </td>

                      </tr>
                      <% end %>
                      </tbody>

                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

</section>