config/routes.rb
Rails.application.routes.draw do

  resources :spare_part_solds
  resources :spare_parts
  resources :quotations
  resources :hydraulic_jacks
  resources :pull_types
  resources :brake_types
  resources :reinforcement_types
  resources :fender_types
  resources :turn_types
  resources :divition_types
  resources :suspension_types
  resources :roof_types
  resources :colors
  resources :trailer_widths
  resources :trailer_lengths
  resources :trailer_heights
  resources :ramp_types
  resources :redila_types
  resources :floor_types
  resources :capacities
  resources :trailer_types
  resources :status_shippings
  resources :fiscal_vouchers
  resources :trailers
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :offices
  get 'items/next_maintenances', to: 'items#next_maintenances', as: :items_next_maintenances
  put 'items/:id/change_maintenance_done/:value', to: 'items#change_maintenance_done', as: :items_change_maintenance_done

  get 'reporter', to: 'items#reporter', as: :reporter

  get '/branches/departments', to: 'branches#departments'

  get '/categories/sub_categories', to: 'categories#sub_categories'

  get '/branches/:id/departments', to: 'branches#departments_for_select'

  get '/terminos_condiciones', to: 'home#terminos_condiciones'

  get '/user_employee_nomber/:employee_nomber', to: 'application#user_employee_nomber'

  delete 'departments/:department_id/employee/:id', to: 'departments#destroy_employee', as: :destroy_department_employee
  delete '/destroy_category/:category_id/:trailer_type_id', to: 'trailer_types#destroy_category'



  mount ActionCable.server, at: '/cable'

  # mount Plutus::Engine => "/plutus", :as => "plutus"

  resources :items
  resources :providers
  resources :maintenances
  resources :status_items
  resources :brands
  resources :sub_categories
  resources :categories
  resources :departments
  resources :branches
  resources :companies
  resources :permissions
  resources :roles
  resources :work_articles


  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do

      put 'sign_up_guest' => 'users_manager#sign_up_guest'
      put 'save_token' => 'users_manager#save_token'
      put 'login_user' => 'users_manager#login_user'
    end
  end

  devise_for :users,
             controllers: {sessions: 'users/sessions',
                           confirmations: 'users/confirmations',
                           unlocks: 'users/unlocks',
                           registrations: 'users/registrations',
                           passwords: 'users/passwords',
                           password_expired: 'users/password_expired'},
             path: '/',
             path_names: {sign_in: 'login',
                          sign_out: 'logout'}

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
      get '/report_to_client/:id' => 'items#report_to_client', :defaults => {:format => 'pdf'}
    end
    get '/users/sessions/remolques_new' => 'users/sessions#remolques_new', as: :login_remolques

    authenticate :user do
      put '/users/assign_item' => 'users/registrations#assign_item', as: :users_assign_item
      put '/users/unassign_item' => 'users/registrations#unassign_item', as: :users_unassign_item

      # Shows all users.
      get '/users', to: 'users/registrations#index', as: :user_registrations
      get '/employees', to: 'users/registrations#employees_index', as: :employees
      get '/employee/:id/assign_work_articles', to: 'users/registrations#assign_work_articles',
          as: :employee_assign_work_articles
      post '/employee/add_work_article', to: 'users/registrations#add_work_article',
           as: :employee_add_work_article
      match '/employee/remove_work_article', to: 'users/registrations#remove_work_article',
            as: :employee_remove_work_article, via: [:patch, :put]
      get '/search_work_articles/:id/:search_type', to: 'users/registrations#search_work_articles',
          as: :search_work_articles

      # Create new users.
      get '/users/new', to: 'users/registrations#new_user', as: :new_user
      get '/employee/new', to: 'users/registrations#new_employee', as: :new_employee
      post '/users', to: 'users/registrations#create_user', as: :create_user



      # Create new users.
      get '/users/employee_department', to: 'users/registrations#new_employee_department', as: :new_employee_department
      #post '/users', to: 'users/registrations#create_user', as: :create_user

      #Get Branch for user
      get '/get_branch_user/:id', to: 'branches#get_branch_user'

      #GET Category and sub category by trailer
      get '/category_subcategory/:id', to: 'trailers#get_category_subcategory'

      # Edit page for a user profile.
      get '/users/edit', to: 'users/registrations#edit', as: :edit_profile
      match '/users', to: 'users/registrations#update_profile', as: :update_profile, via: [:patch, :put]
      match '/users/update_password', to: 'users/registrations#update_password', as: :update_password, via: [:patch, :put]


      # User image
      match '/users/:id/get_user_image', to: 'users/registrations#get_user_image', as: :get_user_image, via: [:patch, :put]

      # Edit page for all users.
      get '/users/:id/edit', to: 'users/registrations#edit_user', as: :edit_user
      match '/users/:id', to: 'users/registrations#update_user', as: :update_user, via: [:patch, :put]

      # Show page for a user.
      get '/users/:id', to: 'users/registrations#show', as: :user

      # Edit a user password.
      get '/users/:id/change_password', to: 'users/registrations#change_password', as: :change_password
      match 'save_password/:id', to: 'users/registrations#save_password', as: :save_password,
            via: [:patch, :put]

      # Destroys a user
      delete '/users/:id', to: 'users/registrations#destroy', as: :destroy_user_registration

      # Gets a JS response with all controller actions.
      get '/permissions/new/get_controller_actions', to: 'permissions#get_controller_actions', as: :get_controller_actions

      # Posts seed data from permissions in relation with their role.
      post '/permissions/generate_seeds', to: 'permissions#generate_seeds', as: :generate_seeds

      # Displays a role with every permission granted.
      get '/roles/:role_id/permissions', to: 'roles#role_permissions', as: :role_permissions

      # Creates a relationship between roles and permissions.
      post '/roles/:role_id/assign_permissions', to: 'roles#assign_permissions', as: :assign_permissions

      # Sets the language to spanish.
      get '/set_language/spanish'

      # Sets the language to english.
      get '/set_language/english'


      #Rutas para la generación de reportes
      get 'reports/sales' => 'reports#report_sales'
      #Rutas para enviar correos
      get '/send_email/:id' => 'items#send_email'


      get '/income_statement' => 'items#income_statement'


      #add Files to Items details from angular
      post '/item_file/:id' => 'items#create_file'
      post '/item_maintenance/:id' => 'items#create_maintenance'
      get '/items_excel' => 'items#items_excel'
      get '/item_qr/:id' => 'items#item_qr', as: :item_qr
      get 'report/sales/:trailers' => 'items#new_report_sales', :defaults => {:format => 'pdf'}
      get 'report/item_sale/:id' => 'items#report_item_sale', :defaults => {:format => 'pdf'}
      get 'download_bill/:id' => 'items#download_bill' #, :defaults => {:format => 'pdf'}


      #add Files to Quotation  from angular
      get 'report/quotation/:id' => 'quotations#report_quotation' #, :defaults => {:format => 'pdf'}

      get 'items_import' => 'items#items_imports'
      resources :items do
        collection { post :import }
      end



      get '/get_maintenances/:id' => 'items#get_maintenances'
      get '/get_files/:id' => 'items#get_files'



      #Regresa la info del articulo que se selecciona en la venta
      get '/cities/:id', to: 'branches#cities'


      get '/next_code_department/:branch_id', to:'branches#next_code'

      #Rutas extras para Departamentos
      get '/departments/:id/items/:employee_id' => 'departments#employee_items', as: :departments_employee_items
      get 'departments_by_branch/:id' => 'departments#get_departments_by_branch'
      get 'all_departments_by_branch/:id' => 'departments#get_all_departments_by_branch'


      #Rutas extras para subcategorias
      get 'subcategory_by_category/:id' => 'sub_categories#get_subcategory_by_category'

      #Ruta para orders
      get 'orders' => 'items#orders'
      get 'orders_shipped' => 'items#orders_shipped'
      get 'new_order' => 'items#new_order', as: :new_order
      get 'edit_order/:id' => 'items#edit_order', as: :edit_order

      #Ruta para cotizaciones
      # get 'quotations' => 'items#quotations'
      # get 'new_quotation' => 'items#new_quotation', as: :new_quotation
      # get 'edit_quotation/:id' => 'items#edit_quotation', as: :edit_quotation

      #Ruta para ventas
      get 'sales' => 'items#sales'
      
      #api
      namespace :api, defaults: {format: 'json'} do
        namespace :v1 do        
          get 'get_items' => 'inventory_manager#get_items'
          get 'get_items_not_sell/:user_id' => 'inventory_manager#get_items_not_sell'
          get 'get_items_sell/:user_id' => 'inventory_manager#get_items_sell'
          get 'get_items_order/:user_id' => 'inventory_manager#get_items_order'
          get 'get_orders_shipped/:user_id' => 'inventory_manager#get_orders_shipped'
          get 'get_branches' => 'inventory_manager#get_branches'
          get 'get_cities' => 'inventory_manager#get_cities'
          get 'get_states' => 'inventory_manager#get_states'
          get 'get_trailers' => 'inventory_manager#get_trailers'

app/models/office.rb
# == Schema Information
#
# Table name: offices
#
#  id            :integer          not null, primary key
#  name          :string
#  description   :text
#  department_id :integer
#  user_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Office < ApplicationRecord
  belongs_to :department
  belongs_to :user
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  before_action :set_office, only: [:show, :edit, :update, :destroy]

  # GET /offices
  # GET /offices.json
  def index
    @search_offices = policy_scope(Office).ransack(params[:q])
    @offices = @search_offices.result.paginate(page: params[:page], per_page: 20)

  end

  # GET /offices/1
  # GET /offices/1.json
  def show
  end

  # GET /offices/new
  def new
    @office = Office.new
  end

  # GET /offices/1/edit
  def edit
  end

  # POST /offices
  # POST /offices.json
  def create
    @office = Office.new(office_params)

    respond_to do |format|
      if @office.save
        format.html { redirect_to offices_path, notice: 'Office was successfully created.' }
        format.json { render :show, status: :created, location: @office }
      else
        format.html { render :new }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /offices/1
  # PATCH/PUT /offices/1.json
  def update
    respond_to do |format|
      if @office.update(office_params)
        format.html { redirect_to offices_path, notice: 'Office was successfully updated.' }
        format.json { render :show, status: :ok, location: @office }
      else
        format.html { render :edit }
        format.json { render json: @office.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /offices/1
  # DELETE /offices/1.json
  def destroy
    @office.destroy
    respond_to do |format|
      format.html { redirect_to offices_url, notice: 'Office was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_office
      @office = Office.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def office_params
      params.require(:office).permit(:name, :description, :department_id, :user_id)
    end
end

app/helpers/offices_helper.rb
module OfficesHelper
end

app/views/offices/_form.html.slim
= form_for(office, role: 'form', html: {class: 'form-horizontal'}, validate: true) do |f|
  .box-body
    .row.form-group
      = f.label :name, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_field :name, class: 'form-control', placeholder: t('.name'), autofocus: true
    .row.form-group
      = f.label :description, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_field :description, class: 'form-control', placeholder: t('.description')
    .row.form-group
      = f.label :deparment, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.collection_select :department, Department.all, :id, :name, {placeholder: t('.department')}, class: 'form-control'
    .row.form-group
      = f.label :user, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.collection_select(:user, User.all, :id, :full_name,
                {prompt: t('helpers.select.prompt')}, {class: 'form-control'})
  .box-footer
    = f.button "<i class='fa fa-floppy-o'></i> #{t('helpers.submit.submit', model: t('.resource'))}".html_safe,
            class: 'btn btn-primary btn-flat', type: 'submit'
    - if has_policy(Office, %w(index))
      = link_to departments_path, class: 'btn btn-default btn-flat' do
        i.fa.fa-list
        =< t('.back')

app/views/offices/edit.html.slim
section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-header.with-border
          h3.box-title
            = t('.title')
        = render 'form', office: @office

app/views/offices/index.html.slim
section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-header.with-border
          .row
            .col-xs-6.col-md-8.col-lg-8
              h3.box-title
                = t('.title')
            .col-xs-6.col-md-4.col-lg-4
              .box-tools.pull-right
                = search_form_for @search_offices do |f|
                  .input-group.input-group-sm.search
                    = f.search_field :name_or_description, class: 'form-control',
                            placeholder: t('helpers.search')
                    .input-group-btn
                      button [class="btn btn-default" type="submit"]
                        i [class="fa fa-search"]
                = link_to new_office_path, class: 'btn btn-sm btn-flat btn-success', title: t('.new_office') do
                  i.fa.fa-plus
                  span.hidden-xs
                    =< t('.new_office')
          //.tools
                  button [type="button" class="btn btn-default btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="false"]
                    i.fa.fa-cog
                  ul [class="dropdown-menu dropdown-menu-right" role="menu"]
                    li
                      a [href="#"]
                        i.fa.fa-file-excel-o
                        = t('helpers.export_excel')
                    li = link_to "<i class='fa fa-file-pdf-o'></i> #{t 'helpers.export_pdf'}".html_safe, reports_rols_path(nombre_reporte: 'rols', titulo_reporte: "Reporte de Usuarios.", format: :pdf)
                    li = link_to "<i class='fa fa-trash'></i> #{t 'helpers.dump_destroy'}".html_safe, '#'
          .box-body
            .dataTables_wrapper
              .row
                .col-sm-12
                  .table-responsive
                    table.table.table-bordered.table-hover.dataTable
                      thead
                        tr
                          th.table-checkbox
                            .checkbox.icheck
                              input [type="checkbox" class="icheck-me" data-skin="square" data-color="blue"]
                          th = t('.name')
                          th = t('.description')
                          th = t('.department')
                          th = t('.user')
                          th.actions_header
                            = t('helpers.actions')
                      tbody
                        - @offices.each do |office|
                          tr.show_actions
                            td.table-checkbox
                              .checkbox.icheck
                                input [type="checkbox" class="icheck-me" data-skin="square" data-color="blue"]
                            td = office.name
                            td = office.description
                            td = office.department
                            td = office.user
                            td
                              .actions
                                = link_item '<i class="fa fa-search"></i>'.html_safe, office_path(office), title: t('helpers.show'),
                                        class: 'btn btn-xs btn-success btn-flat'
                                = link_item '<i class="fa fa-edit"></i>'.html_safe, edit_office_path(office),
                                        class: 'btn btn-xs btn-primary btn-flat', title: t('helpers.edit')
                                - if has_policy(office, %w(destroy))
                                  = link_to '<i class="fas fa-trash"></i>'.html_safe, '#', title: t('helpers.destroy'),
                                          class: 'btn btn-xs btn-danger btn-flat btn-destroy',
                                          data: {'resource' => :roles, 'resource-id' => office.id,
                                                  'resource-message' => t('questions.destroy', resource: t('.resource'),
                                                          name: office.name)}
              .row
                .col-sm-5
                  .dataTables_info
                    = pluralize(@offices.count, t('.one'), t('.other'))
                .col-sm-7
                  .dataTables_paginate.paging_simple_numbers
                    = custom_paginator(@offices)

app/views/offices/new.html.slim
section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-header.with-border
          h3.box-title
            = t('.title')
        = render 'form', office: @office

app/views/offices/show.html.slim
p#notice = notice

p
  strong Name:
  = @office.name
p
  strong Description:
  = @office.description
p
  strong Department:
  = @office.department
p
  strong User:
  = @office.user

= link_to 'Edit', edit_office_path(@office)
'|
= link_to 'Back', offices_path