config/routes.rb
Rails.application.routes.draw do

  resources :spare_part_solds
  resources :spare_parts
  resources :quotations
  resources :hydraulic_jacks
  resources :pull_types
  resources :brake_types
  resources :reinforcement_types
  resources :fender_types
  resources :turn_types
  resources :divition_types
  resources :suspension_types
  resources :roof_types
  resources :colors
  resources :trailer_widths
  resources :trailer_lengths
  resources :trailer_heights
  resources :ramp_types
  resources :redila_types
  resources :floor_types
  resources :capacities
  resources :trailer_types
  resources :status_shippings
  resources :fiscal_vouchers
  resources :trailers
  resources :clients
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :offices
  get 'items/next_maintenances', to: 'items#next_maintenances', as: :items_next_maintenances
  put 'items/:id/change_maintenance_done/:value', to: 'items#change_maintenance_done', as: :items_change_maintenance_done

  get 'reporter', to: 'items#reporter', as: :reporter

  get '/branches/departments', to: 'branches#departments'

  get '/categories/sub_categories', to: 'categories#sub_categories'

  get '/branches/:id/departments', to: 'branches#departments_for_select'

  get '/terminos_condiciones', to: 'home#terminos_condiciones'

  get '/user_employee_nomber/:employee_nomber', to: 'application#user_employee_nomber'

  delete 'departments/:department_id/employee/:id', to: 'departments#destroy_employee', as: :destroy_department_employee
  delete '/destroy_category/:category_id/:trailer_type_id', to: 'trailer_types#destroy_category'



  mount ActionCable.server, at: '/cable'

  # mount Plutus::Engine => "/plutus", :as => "plutus"

  resources :items
  resources :providers
  resources :maintenances
  resources :status_items
  resources :brands
  resources :sub_categories
  resources :categories
  resources :departments
  resources :branches
  resources :companies
  resources :permissions
  resources :roles
  resources :work_articles


  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do

      put 'sign_up_guest' => 'users_manager#sign_up_guest'
      put 'save_token' => 'users_manager#save_token'
      put 'login_user' => 'users_manager#login_user'
    end
  end

  devise_for :users,
             controllers: {sessions: 'users/sessions',
                           confirmations: 'users/confirmations',
                           unlocks: 'users/unlocks',
                           registrations: 'users/registrations',
                           passwords: 'users/passwords',
                           password_expired: 'users/password_expired'},
             path: '/',
             path_names: {sign_in: 'login',
                          sign_out: 'logout'}

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
      get '/report_to_client/:id' => 'items#report_to_client', :defaults => {:format => 'pdf'}
    end
    get '/users/sessions/remolques_new' => 'users/sessions#remolques_new', as: :login_remolques

    authenticate :user do
      put '/users/assign_item' => 'users/registrations#assign_item', as: :users_assign_item
      put '/users/unassign_item' => 'users/registrations#unassign_item', as: :users_unassign_item

      # Shows all users.
      get '/users', to: 'users/registrations#index', as: :user_registrations
      get '/employees', to: 'users/registrations#employees_index', as: :employees
      get '/employee/:id/assign_work_articles', to: 'users/registrations#assign_work_articles',
          as: :employee_assign_work_articles
      post '/employee/add_work_article', to: 'users/registrations#add_work_article',
           as: :employee_add_work_article
      match '/employee/remove_work_article', to: 'users/registrations#remove_work_article',
            as: :employee_remove_work_article, via: [:patch, :put]
      get '/search_work_articles/:id/:search_type', to: 'users/registrations#search_work_articles',
          as: :search_work_articles

      # Create new users.
      get '/users/new', to: 'users/registrations#new_user', as: :new_user
      get '/employee/new', to: 'users/registrations#new_employee', as: :new_employee
      post '/users', to: 'users/registrations#create_user', as: :create_user



      # Create new users.
      get '/users/employee_department', to: 'users/registrations#new_employee_department', as: :new_employee_department
      #post '/users', to: 'users/registrations#create_user', as: :create_user

      #Get Branch for user
      get '/get_branch_user/:id', to: 'branches#get_branch_user'

      #GET Category and sub category by trailer
      get '/category_subcategory/:id', to: 'trailers#get_category_subcategory'

      # Edit page for a user profile.
      get '/users/edit', to: 'users/registrations#edit', as: :edit_profile
      match '/users', to: 'users/registrations#update_profile', as: :update_profile, via: [:patch, :put]
      match '/users/update_password', to: 'users/registrations#update_password', as: :update_password, via: [:patch, :put]


      # User image
      match '/users/:id/get_user_image', to: 'users/registrations#get_user_image', as: :get_user_image, via: [:patch, :put]

      # Edit page for all users.
      get '/users/:id/edit', to: 'users/registrations#edit_user', as: :edit_user
      match '/users/:id', to: 'users/registrations#update_user', as: :update_user, via: [:patch, :put]

      # Show page for a user.
      get '/users/:id', to: 'users/registrations#show', as: :user

      # Edit a user password.
      get '/users/:id/change_password', to: 'users/registrations#change_password', as: :change_password
      match 'save_password/:id', to: 'users/registrations#save_password', as: :save_password,
            via: [:patch, :put]

      # Destroys a user
      delete '/users/:id', to: 'users/registrations#destroy', as: :destroy_user_registration

      # Gets a JS response with all controller actions.
      get '/permissions/new/get_controller_actions', to: 'permissions#get_controller_actions', as: :get_controller_actions

      # Posts seed data from permissions in relation with their role.
      post '/permissions/generate_seeds', to: 'permissions#generate_seeds', as: :generate_seeds

      # Displays a role with every permission granted.
      get '/roles/:role_id/permissions', to: 'roles#role_permissions', as: :role_permissions

      # Creates a relationship between roles and permissions.
      post '/roles/:role_id/assign_permissions', to: 'roles#assign_permissions', as: :assign_permissions

      # Sets the language to spanish.
      get '/set_language/spanish'

      # Sets the language to english.
      get '/set_language/english'


      #Rutas para la generación de reportes
      get 'reports/sales' => 'reports#report_sales'
      #Rutas para enviar correos
      get '/send_email/:id' => 'items#send_email'


      get '/income_statement' => 'items#income_statement'


      #add Files to Items details from angular
      post '/item_file/:id' => 'items#create_file'
      post '/item_maintenance/:id' => 'items#create_maintenance'
      get '/items_excel' => 'items#items_excel'
      get '/item_qr/:id' => 'items#item_qr', as: :item_qr
      get 'report/sales/:trailers' => 'items#new_report_sales', :defaults => {:format => 'pdf'}
      get 'report/item_sale/:id' => 'items#report_item_sale', :defaults => {:format => 'pdf'}
      get 'download_bill/:id' => 'items#download_bill' #, :defaults => {:format => 'pdf'}


      #add Files to Quotation  from angular
      get 'report/quotation/:id' => 'quotations#report_quotation' #, :defaults => {:format => 'pdf'}

      get 'items_import' => 'items#items_imports'
      resources :items do
        collection { post :import }
      end



      get '/get_maintenances/:id' => 'items#get_maintenances'
      get '/get_files/:id' => 'items#get_files'



      #Regresa la info del articulo que se selecciona en la venta
      get '/cities/:id', to: 'branches#cities'


      get '/next_code_department/:branch_id', to:'branches#next_code'

      #Rutas extras para Departamentos
      get '/departments/:id/items/:employee_id' => 'departments#employee_items', as: :departments_employee_items
      get 'departments_by_branch/:id' => 'departments#get_departments_by_branch'
      get 'all_departments_by_branch/:id' => 'departments#get_all_departments_by_branch'


      #Rutas extras para subcategorias
      get 'subcategory_by_category/:id' => 'sub_categories#get_subcategory_by_category'

      #Ruta para orders
      get 'orders' => 'items#orders'
      get 'orders_shipped' => 'items#orders_shipped'
      get 'new_order' => 'items#new_order', as: :new_order
      get 'edit_order/:id' => 'items#edit_order', as: :edit_order

      #Ruta para cotizaciones
      # get 'quotations' => 'items#quotations'
      # get 'new_quotation' => 'items#new_quotation', as: :new_quotation
      # get 'edit_quotation/:id' => 'items#edit_quotation', as: :edit_quotation

      #Ruta para ventas
      get 'sales' => 'items#sales'
      
      #api
      namespace :api, defaults: {format: 'json'} do
        namespace :v1 do        
          get 'get_items' => 'inventory_manager#get_items'
          get 'get_items_not_sell/:user_id' => 'inventory_manager#get_items_not_sell'
          get 'get_items_sell/:user_id' => 'inventory_manager#get_items_sell'
          get 'get_items_order/:user_id' => 'inventory_manager#get_items_order'
          get 'get_orders_shipped/:user_id' => 'inventory_manager#get_orders_shipped'
          get 'get_branches' => 'inventory_manager#get_branches'
          get 'get_cities' => 'inventory_manager#get_cities'
          get 'get_states' => 'inventory_manager#get_states'
          get 'get_trailers' => 'inventory_manager#get_trailers'

app/controllers/home_controller.rb
class HomeController < ApplicationController
  helper_method :sort_column, :sort_direction
  before_action :authenticate_user!, except: [:terminos_condiciones]
  layout false, only: [:terminos_condiciones]

  def index
    redirect_to '/set_language/english' if current_user.role_key.eql?('us_remolques') and session[:locale].eql?(:es)

    unless current_user.nil?
      if current_user.current_company.nil?
        @current_company_state = false
      else

        @current_company_state = true
      end
    end

    @search_departments = policy_scope(Department).ransack(params[:q])
    @departments = @search_departments.result


    @items_count = policy_scope(Item).count
    #@work_articles = WorkArticle.count
    @users = User.all  #policy_scope(User).count

    @items_sold_count = Item.where(status_item_id: [StatusItem.find_by_key('vendido').id,StatusItem.find_by_key('pendiente_factura').id, StatusItem.find_by_key('facturado').id]).count

    @branches_count = policy_scope(Branch).count
    @trailers_count = policy_scope(Trailer).count

    @search_items = policy_scope(Item).ransack(params[:q])

    @total_price_items = @search_items.result.sum(:price)

    @all_models = Trailer.all.pluck(:model)

    @all_remissions = Item.all.pluck(:remission)


    if  params[:column].eql? "Responsable"
      @items = @search_items.result.eager_load(:user).order('users.last_name asc').paginate(page: params[:page], per_page: 20) #if @search_items.sorts.empty?
    elsif params[:column].eql? "branch"
      @items = @search_items.result.eager_load(user: [:branch, {departments: :branch}]).order('branches.name asc, branches_departments.name asc').paginate(page: params[:page], per_page: 20)
    elsif params[:column].eql? "department"
      @items = @search_items.result.eager_load(user: [:department, :departments ]).order("departments.name #{sort_direction}, departments_users #{sort_direction}").paginate(page: params[:page], per_page: 20)
    elsif params[:column].eql? "brand"
      @items = @search_items.result.eager_load(:brand).order("brands.name #{sort_direction}").paginate(page: params[:page], per_page: 20)
    elsif params[:column].eql?("category")
      @items = @search_items.result.eager_load(:category).order("categories.name #{sort_direction}").paginate(page: params[:page], per_page: 20)
    elsif params[:column].eql? "sub_category"
      @items = @search_items.result.eager_load(:sub_category).order("sub_categories.name #{sort_direction}").paginate(page: params[:page], per_page: 20)
    elsif params[:column].eql? "NumEmpleado"
      @items = @search_items.result.eager_load(:user).order("users.employee_number #{sort_direction}").paginate(page: params[:page], per_page: 20)
    else
      @items = @search_items.result.order("#{sort_column.downcase} #{sort_direction}").paginate(page: params[:page], per_page: 20)
      #@items = @search_items.result.eager_load(:user).order('users.last_name asc').paginate(page: params[:page], per_page: 20) #if @search_items.sorts.empty?
    end


    #@search_items.sorts = 'branches.name'
    #@items = @search_items.result.paginate(page: params[:page], per_page: 50)

    #if  params[:column].eql? "Responsable"
    #  @items = @search_items.result.eager_load(:user).order('users.last_name asc').paginate(page: params[:page], per_page: 20) #if @search_items.sorts.empty?
    # elsif params[:column].eql? "branch"
    #   @items = @search_items.result.eager_load(:branch).order("branches.name #{sort_direction}").paginate(page: params[:page], per_page: 20)
    #   #@items = @search_items.order("branches.name #{sort_direction}").paginate(page: params[:page], per_page: 20)
    # elsif params[:column].eql? "department"
    #   @items = @search_items.result.eager_load(:department).order("departments.name #{sort_direction}").paginate(page: params[:page], per_page: 20)
    # elsif params[:column].eql? ("brand") || params[:q][:hola] == '1'
    #   sort_column("brand")
    #   @items = @search_items.result.eager_load(:brand).order("brands.name #{sort_direction}").paginate(page: params[:page], per_page: 20)
    # elsif params[:column].eql?("category")
    #   @items = @search_items.result.eager_load(:category).order("categories.name #{sort_direction}").paginate(page: params[:page], per_page: 20)
    # elsif params[:column].eql? "sub_category"
    #   @items = @search_items.result.eager_load(:sub_category).order("sub_categories.name #{sort_direction}").paginate(page: params[:page], per_page: 20)
    #  else
    #    #@items = @search_items.result.order("#{sort_column.downcase} #{sort_direction}").paginate(page: params[:page], per_page: 20)
    #    #@search_items.sorts = 'items.name'
    #    @items = @search_items.result.eager_load(:user).order('users.last_name asc').paginate(page: params[:page], per_page: 20) #if @search_items.sorts.empty?
    #  end

    #@branches = current_user.current_company.eql?(0) ? policy_scope(Branch).order(:name) : policy_scope(Branch).where(company_id: @current_company.try(:id)).order(:name);


    respond_to do |format|
      format.html
      format.js
    end
  end


  def terminos_condiciones

  end

  private

  def sortable_columns
    ["branch", "department", "category","code", "model", "Responsable", "name", "description", "price", "brand", "sub_category", "NumEmpleado"]
  end

  def sort_column(column=nil)
    if column
      sortable_columns.include?(column) ? column : "code"
    else
      sortable_columns.include?(params[:column]) ? params[:column] : "code"
    end

  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end


end

app/helpers/home_helper.rb
module HomeHelper



  def sort_link(column, title = nil )
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    icon = sort_direction == "asc" ? "fa fa-sort-asc" : "fa fa-sort-desc"
    icon = column == sort_column ? icon : ""
    link_to "#{title} <span class='#{icon}'></span>".html_safe, {column: column, direction: direction}
  end


  def search_branch item
    if item.try(:user).try(:departments).present?
      item.user.departments.last.branch.name
    elsif item.try(:user).try(:department).present?
      item.user.branch.name
    else
      item.try(:user).try(:branches).try(:last).try(:name)
    end
  end

  def search_department item
    if item.try(:user).try(:departments).present?
      item.user.departments.last.name
    elsif item.try(:user).try(:department).present?
      item.user.department.name
    end
  end

end

app/views/home/_list_items_reporter.html.slim
.row
  .col-sm-3
    .dataTables_info
      h4
        span.label.label-success
          = "#{pluralize(@items.count, t('.one'), t('.other'))}"
        = ' '
        span.label.label-primary
          = "#{"#{number_to_currency @total_price_items} #{t('.acquisition_value')}"}"
  .col-sm-9
    .dataTables_paginate.paging_simple_numbers
      = custom_paginator(@items, { controller: 'items', action: 'reporter' })
table.table.table-bordered.table-hover.dataTable
  thead
    tr
      th = t('.serial_number')
      th = t('.model')
      th = 'Descripcion'
      th = t('.branch')
      th = t('.department')
      th.actions_header
        = t('helpers.actions')
  tbody
    - @items.each do |item|
      tr.show_actions
        td = item.serial_number
        td = item.try(:model)
        td = item.categories_description
        td = item.direct_branch.present? ? item.direct_branch.name : (item.direct_branch ? item.direct_branch.name : nil)
        td = item.department.name if item.department.present?
        td
          .actions
            = link_item '<i class="fa fa-search"></i>'.html_safe, item_path(item), title: t('helpers.show'),
                    class: 'btn btn-xs btn-success btn-flat'
            = link_item '<i class="fa fa-edit"></i>'.html_safe, edit_item_path(item),
                    class: 'btn btn-xs btn-primary btn-flat', title: t('helpers.edit')
            - if has_policy(item, %w(destroy))
              / = link_to '<i class="fas fa-trash"></i>'.html_safe, '#', title: t('helpers.destroy'),
                      class: 'btn btn-xs btn-danger btn-flat btn-destroy',
                      data: {'resource' => :items, 'resource-id' => item.id,
                              'resource-message' => t('questions.destroy', resource: t('.resource'),
                                      name: item.name)}

.row
  .col-sm-3
    .dataTables_info
      h4
        span.label.label-success
          = "#{pluralize(@items.count, t('.one'), t('.other'))}"
        = ' '
        span.label.label-primary
          = "#{"#{number_to_currency @total_price_items} #{t('.acquisition_value')}"}"
  .col-sm-9
    .dataTables_paginate.paging_simple_numbers
      = custom_paginator(@items, { controller: 'items', action: 'reporter' , order: 'branch' })
      /= will_paginate @items, renderer: BootstrapPagination::Rails

app/views/home/_remolques_index.html.slim
section.content-header

app/views/home/_reporter.slim
section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-header.with-border
          .row
            .col-xs-6.col-md-8.col-lg-9
              h3.box-title
                = t('.title')
            /.col-xs-6.col-md-4.col-lg-3
            /  .box-tools.pull-right
            /    = search_form_for @search_items do |f|
            /      .input-group.input-group-sm.search
            /        = f.text_field :name_or_description_cont, class: 'form-control',
            /                placeholder: t('helpers.search')
            /        .input-group-btn
            /          button [class="btn btn-default" type="submit"]
            /            i [class="fa fa-search"]
            /    .tools
            /      button [type="button" class="btn btn-default btn-box-tool dropdown-toggle" data-toggle="dropdown" aria-expanded="false"]
            /        i.fa.fa-cog = t('helpers.actions')
            /      ul [class="dropdown-menu dropdown-menu-right" item="menu"]
            /        li = link_to "<i class='fa fa-file-excel-o'></i> #{t 'helpers.export_excel'}".html_safe, items_excel_path(q: params[:q], format: :xlsx)
            /        li = link_to "<i class='fa fa-external-link-square'></i> #{t '.next_maintenances'}".html_safe, items_next_maintenances_path
            /        li
            /          a [href="#"]
            /            i.fa.fa-file-excel-o
            /            = t('helpers.export_excel')
            /        /li = link_to "<i class='fa fa-file-pdf-o'></i> #{t 'helpers.export_pdf'}".html_safe, reports_rols_path(nombre_reporte: 'rols', titulo_reporte: "Reporte de Usuarios.", format: :pdf)
            /        /li = link_to "<i class='fa fa-plus'></i> #{t 'helpers.new'}".html_safe, new_item_path
            /        /li = link_to "<i class='fa fa-trash'></i> #{t 'helpers.dump_destroy'}".html_safe, '#'
          .row
            .box-tools.pull-right
              = search_form_for(@search_items, url: reporter_path, id: 'reporter_form') do |f|
                .row
                /! Ini Brand
                .col-md-3
                  .box.box-warning.box-solid
                    .box-header.with-border
                      h3.box-title = t('.f_brand')
                      .box-tools.pull-right
                        button.btn.btn-box-tool data-widget="collapse" type="button"
                          i.fa.fa-minus
                    .box-body style=('display: block;')
                      = f.collection_select :brand_id_in, Brand.order(:name), :id, :name, {prompt: false},
                              {class: 'form-control select2', multiple: 'multiple', data: {placeholder: t('.brand')}}
                  /! End Brand


                /! Ini Provideer
                .col-md-3
                  .box.box-warning.box-solid
                    .box-header.with-border
                      h3.box-title = t('.f_provider')
                      .box-tools.pull-right
                        button.btn.btn-box-tool data-widget="collapse" type="button"
                          i.fa.fa-minus
                    .box-body style=('display: block;')
                      = f.collection_select :provider_id_in, Provider.order(:name), :id, :name, {prompt: false},
                              {class: 'form-control select2', multiple: 'multiple', data: {placeholder: t('.provider')}}
                  /! End Brand


                /! Ini SubCategory
                .col-md-3
                  .box.box-warning.box-solid
                    .box-header.with-border
                      h3.box-title = t('.f_category')
                      .box-tools.pull-right
                        button.btn.btn-box-tool data-widget="collapse" type="button"
                          i.fa.fa-minus
                    .box-body style=('display: block;')
                      = f.collection_select :category_id_in, Category.order(:name), :id, :name, {prompt: false},
                              {class: 'form-control select2', multiple: 'multiple', data: {placeholder: t('.category')}}
                  /! End SubCategory

                /! Ini SubCategory
                .col-md-3
                  .box.box-warning.box-solid
                    .box-header.with-border
                      h3.box-title = t('.f_sub_category')
                      .box-tools.pull-right
                        button.btn.btn-box-tool data-widget="collapse" type="button"
                          i.fa.fa-minus
                    .box-body style=('display: block;')
                      = f.select(:sub_category_id_in,
                              grouped_options_for_select(Category.all.map{ |c| [c.name, c.sub_categories.order(:id).map{ |sc| [sc.name, sc.id] }] }, selected: params[:q] ? params[:q][:sub_category_id_in] : nil),
                              {prompt: false}, {class: 'form-control select2', multiple: 'multiple', data: {placeholder: t('.sub_category')}})
                  /! End SubCategory



                .row
                /! Ini Status
                .col-md-3
                  .box.box-warning.box-solid
                    .box-header.with-border
                      h3.box-title = t('.f_status_item')
                      .box-tools.pull-right
                        button.btn.btn-box-tool data-widget="collapse" type="button"
                          i.fa.fa-minus
                    .box-body style=('display: block;')
                      = f.collection_select :status_item_id_in, StatusItem.order(:name), :id, :name, {prompt: false},
                              {class: 'form-control select2', multiple: 'multiple', data: {placeholder: t('.status_item')}}
                  /! End Status
                    
                /! Ini Brand
                .col-md-3
                  .box.box-warning.box-solid
                    .box-header.with-border
                      h3.box-title = t('.f_branch')
                      .box-tools.pull-right
                        button.btn.btn-box-tool data-widget="collapse" type="button"
                          i.fa.fa-minus
                    .box-body style=('display: block;')
                      = f.collection_select :branch_id_in, policy_scope(Branch).order(:name), :id, :name, {prompt: false},
                              {class: 'form-control select2', multiple: 'multiple', data: {placeholder: t('.branch')}}
                  /! End Brand

                /! Ini Brand
                .col-md-3
                  .box.box-warning.box-solid
                    .box-header.with-border
                      h3.box-title = t('.f_department')
                      .box-tools.pull-right
                        button.btn.btn-box-tool data-widget="collapse" type="button"
                          i.fa.fa-minus
                    .box-body style=('display: block;')
                      / = f.select(:department_id_in,
                              grouped_options_for_select(Branch.all.map{ |b| [b.name, b.departments.order(:id).map{ |d| [d.name, d.id] }] }, selected: params[:q] ? params[:q][:department_id_in] : nil),
                              {prompt: false}, {class: 'form-control select2', multiple: 'multiple', data: {placeholder: t('.department')}})
                  /! End Brand

                /! Ini Responsible Name
                .col-md-3
                  .box.box-warning.box-solid
                    .box-header.with-border
                      h3.box-title = t('.f_responsible')
                      .box-tools.pull-right
                        button.btn.btn-box-tool data-widget="collapse" type="button"
                          i.fa.fa-minus
                    .box-body style=('display: block;')
                      /= f.text_field :user_first_name_or_user_last_name_or_user_maiden_name_or_department_manager_first_name_or_department_manager_last_name_or_department_manager_maiden_name_or_branch_user_first_name_or_branch_user_last_name_or_branch_user_maiden_name_or_company_user_first_name_or_company_user_last_name_or_company_user_maiden_name_or_direct_branch_user_first_name_or_direct_branch_user_last_name_or_direct_branch_user_maiden_name_or_direct_company_user_first_name_or_direct_company_user_last_name_or_direct_company_user_maiden_name_cont, class: 'form-control', placeholder: t('.responsible')
                      = f.text_field :direct_branch_user_first_name_or_direct_branch_user_last_name_or_direct_branch_user_maiden_name_or_direct_company_user_first_name_or_direct_company_user_last_name_or_direct_company_user_maiden_name_cont, class: 'form-control', placeholder: t('.responsible')
                  /! End Responsible Name

                .col-xs-12.col-md-12
                  .input-group-btn
                    button [class="btn btn-block btn-info btn-lg" type="submit"]
                      i [class="fa fa-search"]
                        = " #{t('.search')}"
        .box-body
          .dataTables_wrapper
            .table-responsive#reporter-list
              = render 'items/list_items_reporter'

app/views/home/index_recover.html.slim
section.content-header
  h1
    | Información general de inventario
    small V 1.0


section.content
    .row

      /! ./col
      .col-lg-3.col-xs-6
        /! small box
        .small-box.bg-blue
          .inner
            h3 = @branches_count
            p Sucursales
          .icon
            i.fa.fa-home
          a.small-box-footer href="/branches"
            | Sucursales
            i.fa.fa-arrow-circle-right

      .col-lg-3.col-xs-6
        /! small box
        .small-box.bg-aqua
          .inner
            h3 = @items_count
            p Artículos
          .icon
            i.fa.fa-tag
          a.small-box-footer href="/items"
            | Lista de articulos
            i.fa.fa-arrow-circle-right
        /! ./col
      .col-lg-3.col-xs-6
        /! small box
        .small-box.bg-green
          .inner
            h3 = @work_articles
            p Artículos de trabajo
          .icon
            i.fa.fa-gavel
          a.small-box-footer href="/employees"
            | Asignación de Arts. de trabajo
            i.fa.fa-arrow-circle-right
      /! ./col
      .col-lg-3.col-xs-6
        /! small box
        .small-box.bg-yellow
          .inner
            h3 = @users
            p Usuarios registrados
          .icon
            i.fa.fa-users
          a.small-box-footer href="/users"
            | Usuarios en el sistema
            i.fa.fa-arrow-circle-right
    .row
      .col-md-12
        .box
            .box-header.with-border
              .row
                .col-xs-6
                  h3.box-title Lista de Empresas
                .col-xs-6
                  .box-tools.pull-right
                    = search_form_for @search_departments, url: authenticated_root_path do |f|
                      .input-group.input-group-sm.search
                        = f.text_field :name_or_branch_name_or_company_name_cont, class: 'form-control',
                                placeholder: t('helpers.search')
                        .input-group-btn
                          button [class="btn btn-default" type="submit"]
                            i [class="fa fa-search"]
            .box-body
              .row

                .col-md-12
                  p.text-center
                    strong Empresas en las cuales se permiten crear empleados y asignación de articulos.
                  .box
                    .box-body.no-padding
                      table.table.table-condensed
                        tbody
                          tr
                            th Compañia
                            th Sucursal
                            th Departamento
                            th style=("width: 40px")  Artículos
                            th style=("width: 40px")  Empleados
                            th Acciones


                          - @departments.each do |department|
                            tr
                              td = department.branch.try(:company).try(:name)
                              td = department.branch_name
                              td = department.name
                              td
                                span.badge.bg-green = department.items.count
                              td
                                span.badge.bg-blue = department.employees.count
                              td
                                = link_item '<i class="fa fa-search"></i> Administrar'.html_safe, department_path(department), title: t('helpers.show'),
                                        class: 'btn btn-xs btn-success btn-flat'



                /! /.box-body

app/views/home/reporter.js.erb
$('#reporter-list').html('<%= escape_javascript(render partial: 'home/list_items_reporter' ) %>');