config/routes.rb
  delete 'departments/:department_id/employee/:id', to: 'departments#destroy_employee', as: :destroy_department_employee
  delete '/destroy_category/:category_id/:trailer_type_id', to: 'trailer_types#destroy_category'



  mount ActionCable.server, at: '/cable'

  # mount Plutus::Engine => "/plutus", :as => "plutus"

  resources :items
  resources :providers
  resources :maintenances
  resources :status_items
  resources :brands
  resources :sub_categories
  resources :categories
  resources :departments
  resources :branches
  resources :companies
  resources :permissions
  resources :roles
  resources :work_articles


  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do

      put 'sign_up_guest' => 'users_manager#sign_up_guest'
      put 'save_token' => 'users_manager#save_token'
      put 'login_user' => 'users_manager#login_user'
    end
  end

  devise_for :users,
             controllers: {sessions: 'users/sessions',
                           confirmations: 'users/confirmations',
                           unlocks: 'users/unlocks',
                           registrations: 'users/registrations',
                           passwords: 'users/passwords',
                           password_expired: 'users/password_expired'},
             path: '/',
             path_names: {sign_in: 'login',
                          sign_out: 'logout'}

  devise_scope :user do
    authenticated :user do
      root 'home#index', as: :authenticated_root
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
      get '/report_to_client/:id' => 'items#report_to_client', :defaults => {:format => 'pdf'}
    end
    get '/users/sessions/remolques_new' => 'users/sessions#remolques_new', as: :login_remolques

    authenticate :user do
      put '/users/assign_item' => 'users/registrations#assign_item', as: :users_assign_item
      put '/users/unassign_item' => 'users/registrations#unassign_item', as: :users_unassign_item

      # Shows all users.
      get '/users', to: 'users/registrations#index', as: :user_registrations
      get '/employees', to: 'users/registrations#employees_index', as: :employees
      get '/employee/:id/assign_work_articles', to: 'users/registrations#assign_work_articles',
          as: :employee_assign_work_articles
      post '/employee/add_work_article', to: 'users/registrations#add_work_article',
           as: :employee_add_work_article
      match '/employee/remove_work_article', to: 'users/registrations#remove_work_article',
            as: :employee_remove_work_article, via: [:patch, :put]
      get '/search_work_articles/:id/:search_type', to: 'users/registrations#search_work_articles',
          as: :search_work_articles

      # Create new users.
      get '/users/new', to: 'users/registrations#new_user', as: :new_user
      get '/employee/new', to: 'users/registrations#new_employee', as: :new_employee
      post '/users', to: 'users/registrations#create_user', as: :create_user



      # Create new users.
      get '/users/employee_department', to: 'users/registrations#new_employee_department', as: :new_employee_department
      #post '/users', to: 'users/registrations#create_user', as: :create_user

      #Get Branch for user
      get '/get_branch_user/:id', to: 'branches#get_branch_user'

      #GET Category and sub category by trailer
      get '/category_subcategory/:id', to: 'trailers#get_category_subcategory'

      # Edit page for a user profile.
      get '/users/edit', to: 'users/registrations#edit', as: :edit_profile
      match '/users', to: 'users/registrations#update_profile', as: :update_profile, via: [:patch, :put]
      match '/users/update_password', to: 'users/registrations#update_password', as: :update_password, via: [:patch, :put]


      # User image
      match '/users/:id/get_user_image', to: 'users/registrations#get_user_image', as: :get_user_image, via: [:patch, :put]

      # Edit page for all users.
      get '/users/:id/edit', to: 'users/registrations#edit_user', as: :edit_user
      match '/users/:id', to: 'users/registrations#update_user', as: :update_user, via: [:patch, :put]

      # Show page for a user.
      get '/users/:id', to: 'users/registrations#show', as: :user

      # Edit a user password.
      get '/users/:id/change_password', to: 'users/registrations#change_password', as: :change_password
      match 'save_password/:id', to: 'users/registrations#save_password', as: :save_password,
            via: [:patch, :put]

      # Destroys a user
      delete '/users/:id', to: 'users/registrations#destroy', as: :destroy_user_registration

      # Gets a JS response with all controller actions.
      get '/permissions/new/get_controller_actions', to: 'permissions#get_controller_actions', as: :get_controller_actions

      # Posts seed data from permissions in relation with their role.
      post '/permissions/generate_seeds', to: 'permissions#generate_seeds', as: :generate_seeds

      # Displays a role with every permission granted.
      get '/roles/:role_id/permissions', to: 'roles#role_permissions', as: :role_permissions

      # Creates a relationship between roles and permissions.
      post '/roles/:role_id/assign_permissions', to: 'roles#assign_permissions', as: :assign_permissions

      # Sets the language to spanish.
      get '/set_language/spanish'

      # Sets the language to english.
      get '/set_language/english'


      #Rutas para la generación de reportes
      get 'reports/sales' => 'reports#report_sales'
      #Rutas para enviar correos
      get '/send_email/:id' => 'items#send_email'


      get '/income_statement' => 'items#income_statement'


      #add Files to Items details from angular
      post '/item_file/:id' => 'items#create_file'
      post '/item_maintenance/:id' => 'items#create_maintenance'
      get '/items_excel' => 'items#items_excel'
      get '/item_qr/:id' => 'items#item_qr', as: :item_qr
      get 'report/sales/:trailers' => 'items#new_report_sales', :defaults => {:format => 'pdf'}
      get 'report/item_sale/:id' => 'items#report_item_sale', :defaults => {:format => 'pdf'}
      get 'download_bill/:id' => 'items#download_bill' #, :defaults => {:format => 'pdf'}


      #add Files to Quotation  from angular
      get 'report/quotation/:id' => 'quotations#report_quotation' #, :defaults => {:format => 'pdf'}

      get 'items_import' => 'items#items_imports'
      resources :items do
        collection { post :import }
      end



      get '/get_maintenances/:id' => 'items#get_maintenances'
      get '/get_files/:id' => 'items#get_files'



      #Regresa la info del articulo que se selecciona en la venta
      get '/cities/:id', to: 'branches#cities'


      get '/next_code_department/:branch_id', to:'branches#next_code'

      #Rutas extras para Departamentos
      get '/departments/:id/items/:employee_id' => 'departments#employee_items', as: :departments_employee_items
      get 'departments_by_branch/:id' => 'departments#get_departments_by_branch'
      get 'all_departments_by_branch/:id' => 'departments#get_all_departments_by_branch'


      #Rutas extras para subcategorias
      get 'subcategory_by_category/:id' => 'sub_categories#get_subcategory_by_category'

      #Ruta para orders
      get 'orders' => 'items#orders'
      get 'orders_shipped' => 'items#orders_shipped'
      get 'new_order' => 'items#new_order', as: :new_order
      get 'edit_order/:id' => 'items#edit_order', as: :edit_order

      #Ruta para cotizaciones
      # get 'quotations' => 'items#quotations'
      # get 'new_quotation' => 'items#new_quotation', as: :new_quotation
      # get 'edit_quotation/:id' => 'items#edit_quotation', as: :edit_quotation

      #Ruta para ventas
      get 'sales' => 'items#sales'
      
      #api
      namespace :api, defaults: {format: 'json'} do
        namespace :v1 do        
          get 'get_items' => 'inventory_manager#get_items'
          get 'get_items_not_sell/:user_id' => 'inventory_manager#get_items_not_sell'
          get 'get_items_sell/:user_id' => 'inventory_manager#get_items_sell'
          get 'get_items_order/:user_id' => 'inventory_manager#get_items_order'
          get 'get_orders_shipped/:user_id' => 'inventory_manager#get_orders_shipped'
          get 'get_branches' => 'inventory_manager#get_branches'
          get 'get_cities' => 'inventory_manager#get_cities'
          get 'get_states' => 'inventory_manager#get_states'
          get 'get_trailers' => 'inventory_manager#get_trailers'
          get 'get_categories' => 'inventory_manager#get_categories'
          get 'get_sub_categories' => 'inventory_manager#get_sub_categories'
          get 'get_status_item' => 'inventory_manager#get_status_item'
          get 'get_status_shipping' => 'inventory_manager#get_status_shipping'
          get 'get_trailer_types' => 'inventory_manager#get_trailer_types'
          get 'get_trailer_categories' => 'inventory_manager#get_trailer_categories'
          get 'get_fiscal_vouchers' => 'inventory_manager#get_fiscal_vouchers'
          get 'get_clients' => 'inventory_manager#get_clients'
          get 'get_items_by_branch/:id' => 'inventory_manager#get_items_by_branch'        
          put 'create_item' => 'inventory_manager#create_item'
          put 'update_item' => 'inventory_manager#update_item'
          put 'create_trailer' => 'trailer_manager#create_trailer'
          put 'update_trailer' => 'trailer_manager#update_trailer'
          put 'create_client' => 'client_manager#create_client'
          put 'update_client' => 'client_manager#update_client'
          delete 'destroy_client' => 'client_manager#destroy_client'
          delete 'destroy_trailer' => 'trailer_manager#destroy_trailer'
          delete 'destroy_item' => 'inventory_manager#destroy_item'
        end
      end
    end
  end

  get '/remolques' => 'items#remolques_index', as: :remolques_items
  get '/remolques/items/new' => 'items#remolques_new', as: :remolques_new_item

app/models/sub_category.rb
# == Schema Information
#
# Table name: sub_categories
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  status      :boolean
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class SubCategory < ApplicationRecord
  belongs_to :category
  has_many :trailers
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
  before_action :set_sub_category, only: [:show, :edit, :update, :destroy]

  # GET /sub_categories
  # GET /sub_categories.json
  def index
    # @search_sub_categories = policy_scope(SubCategory).ransack(params[:q])
    @sub_categories = SubCategory.all
  end

  # GET /sub_categories/1
  # GET /sub_categories/1.json
  def show
  end

  # GET /sub_categories/new
  def new
    @sub_category = SubCategory.new
  end

  # GET /sub_categories/1/edit
  def edit
  end

  # POST /sub_categories
  # POST /sub_categories.json
  def create
    @sub_category = SubCategory.new(sub_category_params)

    respond_to do |format|
      if @sub_category.save
        format.html { redirect_to sub_categories_path, notice: 'La Subcategoría se almaceno correctamente.' }
        format.json { render :show, status: :created, location: @sub_category }
      else
        format.html { render :new }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sub_categories/1
  # PATCH/PUT /sub_categories/1.json
  def update
    respond_to do |format|
      if @sub_category.update(sub_category_params)
        format.html { redirect_to sub_categories_path, notice: 'La Subcategoría se actualizó correctamente.' }
        format.json { render :show, status: :ok, location: @sub_category }
      else
        format.html { render :edit }
        format.json { render json: @sub_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sub_categories/1
  # DELETE /sub_categories/1.json
  def destroy
    @sub_category.destroy
    respond_to do |format|
      format.html { redirect_to sub_categories_url, notice: 'La Subcategoría se eliminó.' }
      format.json { head :no_content }
    end
  end

  def get_subcategory_by_category
    @sub_category = SubCategory.where(category_id: params[:id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sub_category
      @sub_category = SubCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sub_category_params
      params.require(:sub_category).permit(:name, :description, :status, :category_id)
    end
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/sub_categories/_form.html.slim
= form_for(sub_category, sub_category: 'form', html: {class: 'form-horizontal'}, validate: true) do |f|
  - if @sub_category.errors.any?
    #error_explanation
      h2 = "#{pluralize(sub_category.errors.count, "error")} prohibited this sub_category from being saved:"
      ul
        - @sub_category.errors.full_messages.each do |message|
          li = message
  .box-body
    .row.form-group
      = f.label :category, class: 'col-sm-2 control-label'
      .col-sm-10
        /= f.collection_select(:category_id, Category.all, :id, :name,
                {prompt: t('helpers.select.prompt')}, {class: 'form-control'})
        = f.select(:category_id, options_for_select(Category.all.map { |d| [d.name, d.id] }, @sub_category.category_id),
                {prompt: t('helpers.select.prompt')}, {class: 'form-control'})
    .row.form-group
      = f.label :name, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.text_field :name, class: 'form-control', placeholder: t('.name'), autofocus: true
        = f.hidden_field :status, value: true
    / .row.form-group
    /   = f.label 'Codigo', class: 'col-sm-2 control-label'
    /   .col-sm-10
    /     = f.text_field :description, class: 'form-control', placeholder: t('.description')

    .row.form-group
      = f.label :status, class: 'col-sm-2 control-label'
      .col-sm-10
        = f.check_box(:status, {checked: true})
  .box-footer
    = f.button "<i class='fa fa-floppy-o'></i> #{t('helpers.submit.submit', model: t('.resource'))}".html_safe,
            class: 'btn btn-primary btn-flat', type: 'submit'
    = link_to sub_categories_path, class: 'btn btn-default btn-flat' do
      i.fa.fa-list
      =< t('.back')

app/views/sub_categories/edit.html.slim
section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-header.with-border
          h3.box-title
            = t('.title')
        = render 'form', sub_category: @sub_category

app/views/sub_categories/index.html.slim
section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-header.with-border
          .row
            .col-xs-6.col-md-8.col-lg-8
              h3.box-title
                = t('.title')
            .col-xs-6.col-md-4.col-lg-4
              .box-tools.pull-right
                = link_to new_sub_category_path, class: 'btn btn-sm btn-flat btn-success', title: t('.new_sub_category') do
                  i.fa.fa-plus
                  span.hidden-xs
                    =< t('.new_sub_category')


            .box-body
              .dataTables_wrapper
                .row
                  .col-sm-12
                    .table-responsive
                      table.table.table-bordered.table-hover.dataTable
                        thead
                          tr
                            /th.table-checkbox
                              .checkbox.icheck
                                input [type="checkbox" class="icheck-me" data-skin="square" data-color="blue"]
                            th = t('.category')
                            th = t('.name')
                            / th = t('.description')
                            /th = t('.status')
                            th.actions_header
                              = t('helpers.actions')
                          tbody
                            - @sub_categories.each do |sub_category|
                              tr.show_actions
                                /td.table-checkbox
                                  .checkbox.icheck
                                    input [type="checkbox" class="icheck-me" data-skin="square" data-color="blue"]
                                td = sub_category.category.try("name")
                                td = sub_category.name
                                / td = sub_category.description
                                / td = sub_category.status ? 'Activo' : 'Inhábil'
                                td
                                  .actions
                                    = link_item '<i class="fa fa-edit"></i>'.html_safe, edit_sub_category_path(sub_category),
                                            class: 'btn btn-xs btn-primary btn-flat', title: t('helpers.edit')
                                    - if has_policy(sub_category, %w(destroy))
                                      = link_to '<i class="fas fa-trash"></i>'.html_safe, sub_category_path(sub_category), method: :delete, title: t('helpers.destroy'),
                                              class: 'btn btn-xs btn-danger btn-flat btn-destroy',
                                              data: {'resource' => :sub_categories, 'resource-id' => sub_category.id,
                                                      'resource-message' => t('questions.destroy', resource: t('.resource'),
                                                              name: sub_category.name)}
          .row
            .col-sm-5
              .dataTables_info
                = pluralize(@sub_categories.count, t('.one'), t('.other'))

app/views/sub_categories/new.html.slim
section.content
  .row
    .col-xs-12
      .box.box-primary
        .box-header.with-border
          h3.box-title
            = t('.title')
        = render 'form', sub_category: @sub_category

app/views/sub_categories/show.html.slim
p#notice = notice

p
  strong Name:
  = @sub_category.name
p
  strong Description:
  = @sub_category.description
p
  strong Status:
  = @sub_category.status
p
  strong Category:
  = @sub_category.category

= link_to 'Edit', edit_sub_category_path(@sub_category)
'|
= link_to 'Back', sub_categories_path